import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// ✅ TODO: Concluir si puede entrar el ThemeProvider
// import { ThemeProvider } from "@/components/theme-provider";
import Sidebar from "@/components/Sidebar";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body className={cn("antialiased min-h-screen flex", inter.className)}>
          
            <Sidebar />
            {children}
        </body>
      </html>
    </>
  );
}
