import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// ✅ TODO: Concluir si puede entrar el ThemeProvider
// import { ThemeProvider } from "@/components/theme-provider";
import Sidebar from "@/components/Sidebar";
import Footer from "@/components/Footer";
import { cn } from "@/lib/utils";
import DotPattern from "@/components/magicui/DotPattern";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body className={cn("antialiased min-h-screen", inter.className)}>
          <Sidebar />
          {children}
          <Footer />
          <DotPattern
            width={20}
            height={20}
            cx={1}
            cy={1}
            cr={1}
            className={cn(
              "[mask-image:linear-gradient(to_bottom_right,white,transparent,transparent)] "
            )}
          />
        </body>
      </html>
    </>
  );
}
